name: Flutter CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: "16.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.8

      - run: flutter pub get
      - run: flutter analyze

      - name: Run Unit Tests
        run: flutter test

      - name: Run Integration Tests
        run: flutter drive  --target=integration_test/app_test.dart --driver=integration_test/login_scenario.dart

      - run: flutter build apk
      - name: List contents of flutter-apk directory
        run: ls -R build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/app/outputs/flutter-apk/